apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../deploy/ai-agent
images:
  - name: aiops-agent
    newName: ghcr.io/brucorreia/aiops-agent
    newTag: "1e247e2"
patches:
  - target:
      kind: Deployment
      name: ai-agent
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
