apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../deploy/demo-app
images:
  - name: aiops-demo-app
    newName: ghcr.io/brucorreia/aiops-demo-app
    newTag: "7cb7e56"
patches:
  - target:
      kind: Deployment
      name: demo-app
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/imagePullPolicy
        value: Always
      - op: replace
        path: /spec/template/spec/containers/0/env
        value:
          - name: SERVICE_NAME
            value: demo-app
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/resources/requests/memory
        value: 16Mi
      - op: replace
        path: /spec/template/spec/containers/0/resources/limits/memory
        value: 32Mi
